[toolchain]
anchor_version = "0.31.1"

[features]
resolution = true
skip-lint = false

[programs.devnet]
games_hub_bets = "CGU9v9Zt1PJECyZDcXVJpgzjukxy2ejAXbN1bUbGE8tq"

[programs.localnet]
games_hub_bets = "CGU9v9Zt1PJECyZDcXVJpgzjukxy2ejAXbN1bUbGE8tq"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = ["programs/*"]
resolver = "2"
