use anchor_lang::prelude::*;

// `anchor keys sync` fills this from the program keypair generated by Anchor.
declare_id!("CGU9v9Zt1PJECyZDcXVJpgzjukxy2ejAXbN1bUbGE8tq");

const ONE_SOL: u64 = 1_000_000_000;
const MATCH_TIMEOUT_SECONDS: i64 = 60 * 60;
const WAITING: u8 = 0;
const ACTIVE: u8 = 1;
const SETTLED: u8 = 2;
const CANCELLED: u8 = 3;

#[program]
pub mod games_hub_bets {
    use super::*;

    /// Opens a wager by escrowing exactly 1 SOL and selecting the match referee.
    pub fn create_sol_match(ctx: Context<CreateSolMatch>, match_id: Pubkey, stake: u64) -> Result<()> {
        require!(stake == ONE_SOL, BetError::WrongStake);

        let state = &mut ctx.accounts.match_state;
        state.id = match_id;
        state.player_one = ctx.accounts.player_one.key();
        state.player_two = Pubkey::default();
        state.referee = ctx.accounts.referee.key();
        state.winner = Pubkey::default();
        state.stake = stake;
        state.expires_at = 0;
        state.status = WAITING;
        state.bump = ctx.bumps.match_state;
        state.escrow_bump = ctx.bumps.escrow;

        anchor_lang::system_program::transfer(
            CpiContext::new(
                ctx.accounts.system_program.to_account_info(),
                anchor_lang::system_program::Transfer {
                    from: ctx.accounts.player_one.to_account_info(),
                    to: ctx.accounts.escrow.to_account_info(),
                },
            ),
            stake,
        )?;
        Ok(())
    }

    /// Joins an open match and escrows the second 1 SOL stake.
    pub fn join_sol_match(ctx: Context<JoinSolMatch>, match_id: Pubkey) -> Result<()> {
        let state = &mut ctx.accounts.match_state;
        require!(state.id == match_id, BetError::InvalidMatchId);
        require!(state.status == WAITING, BetError::MatchNotWaiting);
        require!(ctx.accounts.player_two.key() != state.player_one, BetError::SamePlayer);

        anchor_lang::system_program::transfer(
            CpiContext::new(
                ctx.accounts.system_program.to_account_info(),
                anchor_lang::system_program::Transfer {
                    from: ctx.accounts.player_two.to_account_info(),
                    to: ctx.accounts.escrow.to_account_info(),
                },
            ),
            state.stake,
        )?;

        state.player_two = ctx.accounts.player_two.key();
        state.status = ACTIVE;
        state.expires_at = Clock::get()?
            .unix_timestamp
            .checked_add(MATCH_TIMEOUT_SECONDS)
            .ok_or(BetError::MathOverflow)?;
        Ok(())
    }

    /// Pays both stakes (2 SOL total) to the winner selected by the referee.
    pub fn settle_sol_match(ctx: Context<SettleSolMatch>, winner: Pubkey) -> Result<()> {
        let state = &mut ctx.accounts.match_state;
        require!(state.status == ACTIVE, BetError::MatchNotActive);
        require!(winner == state.player_one || winner == state.player_two, BetError::InvalidWinner);
        require_keys_eq!(ctx.accounts.winner_wallet.key(), winner, BetError::WrongWinnerAccount);
        require_keys_eq!(ctx.accounts.player_one_wallet.key(), state.player_one, BetError::WrongPlayerAccount);

        let payout = state.stake.checked_mul(2).ok_or(BetError::MathOverflow)?;
        transfer_lamports(
            &ctx.accounts.escrow.to_account_info(),
            &ctx.accounts.winner_wallet.to_account_info(),
            payout,
        )?;
        // Return the escrow account's rent reserve to its creator.
        let remainder = ctx.accounts.escrow.lamports();
        transfer_lamports(
            &ctx.accounts.escrow.to_account_info(),
            &ctx.accounts.player_one_wallet.to_account_info(),
            remainder,
        )?;

        state.winner = winner;
        state.status = SETTLED;
        Ok(())
    }

    /// Refunds both players after one hour if the referee has not settled the match.
    pub fn refund_sol_match(ctx: Context<RefundSolMatch>) -> Result<()> {
        let state = &mut ctx.accounts.match_state;
        require!(state.status == ACTIVE, BetError::MatchNotActive);
        require!(Clock::get()?.unix_timestamp >= state.expires_at, BetError::RefundNotAvailable);
        require_keys_eq!(ctx.accounts.player_one_wallet.key(), state.player_one, BetError::WrongPlayerAccount);
        require_keys_eq!(ctx.accounts.player_two_wallet.key(), state.player_two, BetError::WrongPlayerAccount);

        transfer_lamports(
            &ctx.accounts.escrow.to_account_info(),
            &ctx.accounts.player_one_wallet.to_account_info(),
            state.stake,
        )?;
        transfer_lamports(
            &ctx.accounts.escrow.to_account_info(),
            &ctx.accounts.player_two_wallet.to_account_info(),
            state.stake,
        )?;
        let remainder = ctx.accounts.escrow.lamports();
        transfer_lamports(
            &ctx.accounts.escrow.to_account_info(),
            &ctx.accounts.player_one_wallet.to_account_info(),
            remainder,
        )?;
        state.status = CANCELLED;
        Ok(())
    }

    /// Lets the creator reclaim the stake if nobody has joined yet.
    pub fn cancel_sol_match(ctx: Context<CancelSolMatch>) -> Result<()> {
        let state = &mut ctx.accounts.match_state;
        require!(state.status == WAITING, BetError::MatchNotWaiting);
        require_keys_eq!(ctx.accounts.player_one.key(), state.player_one, BetError::WrongPlayerAccount);

        let remainder = ctx.accounts.escrow.lamports();
        transfer_lamports(
            &ctx.accounts.escrow.to_account_info(),
            &ctx.accounts.player_one.to_account_info(),
            remainder,
        )?;
        state.status = CANCELLED;
        Ok(())
    }
}

fn transfer_lamports(from: &AccountInfo, to: &AccountInfo, amount: u64) -> Result<()> {
    let from_balance = from.lamports();
    let to_balance = to.lamports();
    **from.try_borrow_mut_lamports()? = from_balance.checked_sub(amount).ok_or(BetError::MathOverflow)?;
    **to.try_borrow_mut_lamports()? = to_balance.checked_add(amount).ok_or(BetError::MathOverflow)?;
    Ok(())
}

#[derive(Accounts)]
#[instruction(match_id: Pubkey, stake: u64)]
pub struct CreateSolMatch<'info> {
    #[account(init, payer = player_one, space = SolMatch::LEN, seeds = [b"sol_match", match_id.as_ref()], bump)]
    pub match_state: Account<'info, SolMatch>,
    /// CHECK: This zero-data PDA is program-owned and its seeds bind it to this match.
    #[account(init, payer = player_one, space = 0, owner = crate::ID, seeds = [b"sol_escrow", match_id.as_ref()], bump)]
    pub escrow: UncheckedAccount<'info>,
    /// CHECK: Its key is stored in match state and must sign settlement.
    pub referee: UncheckedAccount<'info>,
    #[account(mut)]
    pub player_one: Signer<'info>,
    pub system_program: Program<'info, System>,
}

#[derive(Accounts)]
#[instruction(match_id: Pubkey)]
pub struct JoinSolMatch<'info> {
    #[account(mut, seeds = [b"sol_match", match_id.as_ref()], bump = match_state.bump)]
    pub match_state: Account<'info, SolMatch>,
    /// CHECK: Match-bound program-owned SOL escrow PDA.
    #[account(mut, seeds = [b"sol_escrow", match_id.as_ref()], bump = match_state.escrow_bump, owner = crate::ID)]
    pub escrow: UncheckedAccount<'info>,
    #[account(mut)]
    pub player_two: Signer<'info>,
    pub system_program: Program<'info, System>,
}

#[derive(Accounts)]
#[instruction(winner: Pubkey)]
pub struct SettleSolMatch<'info> {
    #[account(mut, close = player_one_wallet, seeds = [b"sol_match", match_state.id.as_ref()], bump = match_state.bump, has_one = referee)]
    pub match_state: Account<'info, SolMatch>,
    /// CHECK: Match-bound program-owned SOL escrow PDA.
    #[account(mut, seeds = [b"sol_escrow", match_state.id.as_ref()], bump = match_state.escrow_bump, owner = crate::ID)]
    pub escrow: UncheckedAccount<'info>,
    /// CHECK: Handler requires this to match the selected winner.
    #[account(mut)]
    pub winner_wallet: UncheckedAccount<'info>,
    /// CHECK: Handler requires this to match the creator and returns escrow rent here.
    #[account(mut)]
    pub player_one_wallet: UncheckedAccount<'info>,
    pub referee: Signer<'info>,
}

#[derive(Accounts)]
pub struct RefundSolMatch<'info> {
    #[account(mut, close = player_one_wallet, seeds = [b"sol_match", match_state.id.as_ref()], bump = match_state.bump)]
    pub match_state: Account<'info, SolMatch>,
    /// CHECK: Match-bound program-owned SOL escrow PDA.
    #[account(mut, seeds = [b"sol_escrow", match_state.id.as_ref()], bump = match_state.escrow_bump, owner = crate::ID)]
    pub escrow: UncheckedAccount<'info>,
    /// CHECK: Handler checks the stored player one key.
    #[account(mut)]
    pub player_one_wallet: UncheckedAccount<'info>,
    /// CHECK: Handler checks the stored player two key.
    #[account(mut)]
    pub player_two_wallet: UncheckedAccount<'info>,
}

#[derive(Accounts)]
pub struct CancelSolMatch<'info> {
    #[account(mut, close = player_one, seeds = [b"sol_match", match_state.id.as_ref()], bump = match_state.bump)]
    pub match_state: Account<'info, SolMatch>,
    /// CHECK: Match-bound program-owned SOL escrow PDA.
    #[account(mut, seeds = [b"sol_escrow", match_state.id.as_ref()], bump = match_state.escrow_bump, owner = crate::ID)]
    pub escrow: UncheckedAccount<'info>,
    #[account(mut)]
    pub player_one: Signer<'info>,
}

#[account]
#[derive(Default)]
pub struct SolMatch {
    pub id: Pubkey,
    pub player_one: Pubkey,
    pub player_two: Pubkey,
    pub referee: Pubkey,
    pub winner: Pubkey,
    pub stake: u64,
    pub expires_at: i64,
    pub status: u8,
    pub bump: u8,
    pub escrow_bump: u8,
}

impl SolMatch {
    pub const LEN: usize = 8 + 32 * 5 + 8 + 8 + 3;
}

#[error_code]
pub enum BetError {
    #[msg("This wager requires an exact 1 SOL stake")]
    WrongStake,
    #[msg("The match ID does not match its account")]
    InvalidMatchId,
    #[msg("This match is not waiting for a second player")]
    MatchNotWaiting,
    #[msg("A player cannot join their own match")]
    SamePlayer,
    #[msg("This match is not active")]
    MatchNotActive,
    #[msg("The winner must be one of the two players")]
    InvalidWinner,
    #[msg("The winner wallet account does not match the selected winner")]
    WrongWinnerAccount,
    #[msg("The supplied account does not match the stored player")]
    WrongPlayerAccount,
    #[msg("Refunds are available one hour after the match starts")]
    RefundNotAvailable,
    #[msg("Lamport arithmetic overflow")]
    MathOverflow,
}
